<?php

namespace App\Exports\Sales;

use Maatwebsite\Excel\Concerns\FromCollection;
use Maatwebsite\Excel\Concerns\WithHeadings;
use Maatwebsite\Excel\Concerns\WithMapping;
use Maatwebsite\Excel\Concerns\ShouldAutoSize;
use Maatwebsite\Excel\Concerns\WithStyles;
use PhpOffice\PhpSpreadsheet\Worksheet\Worksheet;
use Illuminate\Support\Collection;

class SalesOrderExport implements FromCollection, WithHeadings, WithMapping, ShouldAutoSize, WithStyles
{
    public function __construct(
        protected Collection $collection
    ) {}

    public function collection()
    {
        $footer = (object) [
            'is_footer' => true,
            'message' => 'Generated by System on ' . now()->format('d M Y, H:i:s')
        ];
        
        return $this->collection->push($footer);
    }

    public function headings(): array
    {
        return [
            'SO NUM',
            'DATE',
            'CUSTOMER NAME',
            'PROJECT NAME',
            'STATUS',
            'BRANCH CODE',
            'TOTAL',
            'DELIVERY DATE',
        ];
    }

    public function map($row): array
    {
        if (isset($row->is_footer)) {
            return [$row->message];
        }

        return [
            $row->sales_order_number,
            $row->date,
            $row->customer_name,
            $row->project_name ?? '-',
            $row->status ? 'Approved' : 'Pending',
            $row->branch_code,
            $row->net_price,
            $row->delivery_date,
        ];
    }

    public function styles(Worksheet $sheet)
    {
        return [
            1 => ['font' => ['bold' => true]],
        ];
    }
}
