<?php

namespace App\Exports\Purchasing;

use Maatwebsite\Excel\Concerns\FromCollection;
use Maatwebsite\Excel\Concerns\WithHeadings;
use Maatwebsite\Excel\Concerns\WithMapping;
use Maatwebsite\Excel\Concerns\ShouldAutoSize;
use Maatwebsite\Excel\Concerns\WithStyles;
use PhpOffice\PhpSpreadsheet\Worksheet\Worksheet;
use Illuminate\Support\Collection;

class LandedCostExport implements FromCollection, WithHeadings, WithMapping, ShouldAutoSize, WithStyles
{
    public function __construct(
        protected Collection $collection
    ) {}

    public function collection()
    {
        $footer = (object) [
            'is_footer' => true,
            'message' => 'Generated by System on ' . now()->format('d M Y, H:i:s')
        ];
        
        return $this->collection->push($footer);
    }

    public function headings(): array
    {
        return [
            'LANDED COST NUM',
            'RECEIVING NUMBER',
            'LANDED COST DATE',
            'PO NUM',
            'SUPPLIER CODE',
            'CURRENCY',
            'CURRENCY RATE',
            'EXWORK',
            'FACTOR COST',
            'CREATED BY',
            'CREATED AT',
        ];
    }

    public function map($row): array
    {
        if (isset($row->is_footer)) {
            return [$row->message];
        }

        return [
            $row->landed_cost_number,
            $row->receiving_number,
            $row->landed_cost_date,
            $row->purchase_order_number,
            $row->supplier_code,
            $row->currency_code,
            $row->currency_rate,
            $row->sub_total,
            $row->factor_cost,
            $row->created_by,
            $row->created_at,
        ];
    }

    public function styles(Worksheet $sheet)
    {
        return [
            1 => ['font' => ['bold' => true]],
        ];
    }
}
