<?php

namespace App\Exports\Purchasing;

use Maatwebsite\Excel\Concerns\FromCollection;
use Maatwebsite\Excel\Concerns\WithHeadings;
use Maatwebsite\Excel\Concerns\WithMapping;
use Maatwebsite\Excel\Concerns\ShouldAutoSize;
use Maatwebsite\Excel\Concerns\WithStyles;
use PhpOffice\PhpSpreadsheet\Worksheet\Worksheet;
use Illuminate\Support\Collection;

class ReceivingExport implements FromCollection, WithHeadings, WithMapping, ShouldAutoSize, WithStyles
{
    public function __construct(
        protected Collection $collection
    ) {}

    public function collection()
    {
        $footer = (object) [
            'is_footer' => true,
            'message' => 'Generated by System on ' . now()->format('d M Y, H:i:s')
        ];
        
        return $this->collection->push($footer);
    }

    public function headings(): array
    {
        return [
            'RECEIVING NUM',
            'DATE',
            'STATUS',
            'SUPPLIER INVOICE',
            'PO NUM',
            'SUPPLIER',
            'WAREHOUSE',
            'GRAND TOTAL',
            'APPROVED BY',
            'APPROVAL DATE',
            'INVENTORY TYPE',
            'CREATED AT',
        ];
    }

    public function map($row): array
    {
        if (isset($row->is_footer)) {
            return [$row->message];
        }

        return [
            $row->receiving_number,
            $row->date,
            $row->status ? 'Approved' : 'Pending',
            $row->supplier_invoice_number,
            $row->purchase_order_number,
            $row->supplier_name,
            $row->warehouse_name,
            $row->grand_total,
            $row->approved_by,
            $row->approval_date,
            $row->inventory_type,
            $row->created_at,
        ];
    }

    public function styles(Worksheet $sheet)
    {
        return [
            1 => ['font' => ['bold' => true]],
        ];
    }
}
