import type { PaginateFilter } from '@/types/common/paginate.types';

export interface PurchaseOrder {
    id: number;
    branch_code: string;
    purchase_order_number: string;
    date: string | null;
    status: boolean;
    approved_by: string | null;
    approval_date: string | null;
    is_inclusive_tax: boolean;
    tax_percentage: number;
    tax_base_amount: number;
    tax_base_amount_rupiah: number;
    tax_amount: number;
    tax_amount_rupiah: number;
    discount_percentage_1: number;
    discount_amount_1: number;
    discount_percentage_2: number;
    discount_amount_2: number;
    discount_percentage_3: number;
    discount_amount_3: number;
    sub_total: number;
    sub_total_rupiah: number;
    grand_total: number;
    grand_total_rupiah: number;
    category: string;
    supplier_code: string;
    supplier_name: string;
    supplier_id: number;
    supplier_address: string | null;
    supplier_country: string | null;
    supplier_city: string | null;
    supplier_phone: string | null;
    supplier_contact_person: string | null;
    is_general_purchase: boolean;
    is_consignment: boolean;
    is_local_purchase: boolean;
    is_repacking: boolean;
    delivery_date: string | null;
    delivery_date_revision: string | null;
    due_date: string | null;
    inventory_type: string;
    department_name: string;
    department_id: number;
    department_code: string;
    currency_code: string;
    currency_rate: number;
    supplier_payment_term: string | null;
    supplier_delivery_term: string | null;
    price_condition: string | null;
    packing_information: string | null;
    delivery_date_information: string | null;
    shipment_information: string | null;
    destination_information: string | null;
    payment_information: string | null;
    insurance_information: string | null;
    remark1: string | null;
    remark2: string | null;
    freight_charge: number;
    other_charge: number;
    other_expenses: number;
    other_expenses_remark: string | null;
    created_by: string;
    created_at: string | null;
    updated_at: string | null;
}

export interface PurchaseOrderFilters extends PaginateFilter {
    start_date?: string;
    end_date?: string;
}
